name: Deploy Dev

on:
  push:
    branches: [ main-mobile-dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        run: |
          curl -X POST \
               -H "Authorization: Bearer ${{ secrets.RENDER_TOKEN }}" \
               -H "Accept: application/json" \
               -d '' \
               https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID_DEV }}/deploys
